### ISSUE TITLE
How to Run YOLO2 trained model on webcam in java

### ISSUE THREAD

**Issue by msarfrazcss** [szaza/tensorflow-example-java#2]
Hey guys, It was success to run YOLO2 trained model on Image, but anyone can help me please to run this model on live webcam for object detection. Or any other help to do so.

Thanks in advance.

**Comment by szaza** [comment]
Hi,
I didn't try such a thing, but I would use a library to capture images from webcam then I would pass the image to the YOLOv2 input.

Here you can find several example projects to capture image from webcam:
- http://webcam-capture.sarxos.pl/;
- https://stackoverflow.com/questions/11487251/best-way-to-access-web-camera-in-java;
- https://stackoverflow.com/questions/276292/capturing-image-from-webcam-in-java;

Best regards,
   Zoltan

**Comment by msarfrazcss** [comment]
Thanks, What about JavaCV to do so.

**Comment by szaza** [comment]
I'm not so familiar with the JavaCV, however based on the descriptions what I've found it should work.
You can use something like this: http://ganeshtiwaridotcomdotnp.blogspot.com/2011/12/javacv-capture-save-flip-show-live.html;
Good luck for your work!

**Comment by msarfrazcss** [comment]
Hi,
I have got success to capture images from webcam then I passed the image to the YOLOv2 input. and then i am showing that processed image onto webcam to display detected object. But it is taking almost 30 seconds to from taken image to display on webcam, it is too much slow.

Can we not detect webcam frame directly onto webcam, or any other help.

One more question have you any python script that could run this model on webcam.

Second question is: This JAVA code running without JNI library, if i add JNI library then it gives error like this:

Exception in thread "main" java.lang.IllegalArgumentException: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: 0-convolutional = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](Pad, 0-convolutional/filter)
	at org.tensorflow.Graph.importGraphDef(Native Method)
	at org.tensorflow.Graph.importGraphDef(Graph.java:130)
	at org.tensorflow.Graph.importGraphDef(Graph.java:114)
	at com.tensorflow.ObjectDetector.executeYOLOGraph(ObjectDetector.java:102)
	at com.tensorflow.ObjectDetector.detect(ObjectDetector.java:54)
	at com.tensorflow.Main.main(Main.java:12)

**Comment by msarfrazcss** [comment]
> Hi,
> Darknet has a feature to capture images from the webcam and run detection on them. It has been written in C/C++ and it is the reference framework for YOLOv2. Have a look at the page here: https://pjreddie.com/darknet/yolo/, section: Real-Time Detection on a Webcam.
> I also had problems with the JNI library and unfortunately, I didn't find any solution so far.
Can we detect webcam image in **DarkFlow** , and can we do this in java.

**Comment by msarfrazcss** [comment]
And One more thing your code can be run on YOLO-V3 model?

**Comment by szaza** [comment]
Theoretically DarkFlow implementatin supports webcam image capturing, however it was developed in Python: https://github.com/thtrieu/darkflow;
At the moment my implementation does not support the YOLO-V3 model.

**Comment by msarfrazcss** [comment]
Thanks a lot @szaza

**Comment by szaza** [comment]
You're welcome!

**Comment by dreistheman** [comment]
@msarfrazcss Were you able to come up with a reasonably fast approach with your problem?
