### ISSUE TITLE
ERROR to load trained YOLOV2 model in java

### ISSUE THREAD

**Issue by msarfrazcss** [szaza/tensorflow-example-java#4]
Hi,

I have trained my model in **Darkflow** by using **tiny-yolo-voc.weights** on 2300 images, and i have trained this model on 36000 step, but when i am using this model it giving error at the highlighted line:

try (Graph graph = new Graph()) {
            **graph.importGraphDef(GRAPH_DEF);**
            try (Session sess = new Session(graph);
                Tensor<Float> result = sess.runner().feed("input", image).fetch("output").run().get(0).expect(Float.class)) {
                float[] outputTensor = new float[YOLOClassifier.getInstance().getOutputSizeByShape(result)];
                FloatBuffer floatBuffer = FloatBuffer.wrap(outputTensor);
                result.writeTo(floatBuffer);
                return outputTensor;
            }
        }

ERROR is:
Exception in thread "main" java.lang.IllegalArgumentException: **graphDef and prefix cannot be null**
	at org.tensorflow.Graph.importGraphDef(Graph.java:127)
	at org.tensorflow.Graph.importGraphDef(Graph.java:114)

Can you please tell me where i am going wrong?
Tensorflow version was same at training and load time, it is: 1.11.0
OS: MCOSX (Using CPU, not GPU)

**Comment by msarfrazcss** [comment]
Sorry, it has been resolved, it was file naming problem.

**Comment by dreistheman** [comment]
@msarfrazcss I have the same problem now. What's the correct file naming convention then for the .pb and labels .txt?

**Comment by szaza** [comment]
Hi,
It is indifferent how you name those files, just don't forget to adapt in the configuration file:
https://github.com/szaza/tensorflow-example-java/blob/master/src/main/java/edu/ml/tensorflow/Config.java
